### ISSUE TITLE
Questions about concentration estimation

### ISSUE THREAD

**Issue by Knarf04** [salesforce/PCL#1]
Hi,

Your work is great! I've went through your paper and your code, and I think that your improvements made on MoCo is very clever. I'm just a little confused about part 3.3 of your paper, where you presented a concentration estimation. What do you mean by similar concentration? Could you provide two visualized examples of similar concentration but obviously different sizes? I know it shouldn't be the case in your method since you've intentionally maintained balanced clusters, but I just want to understand this concept more intuitively. It would be even better if you could also explain how you end up with that formula for phi.

Sorry if the questions sound dumb, but I'm new to this area and would really appreciate any help.

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest!

A higher concentration could be caused by (1) the samples in this cluster are closer to the centroid, or (2) there are more samples in this cluster. Regarding to your question, a cluster with few samples that are closer to the centroid would have similar concentration with a cluster with more samples but the samples are more separated.

With this intuition in mind, phi can be interpreted as 'average distance to centroid / log(number of samples + constant)'. The use of log and the constant is a heuristic choice to maintain a proper scale.

**Comment by Knarf04** [comment]
Thank you!
